# Generated by Django 5.0.3 on 2024-03-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_alter_stockdata_close_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='ticker_symbol',
            field=models.CharField(max_length=20),
        ),
    ]
